### ISSUE TITLE
Test fail in v0.8.0

### ISSUE THREAD

**Issue by bemeyert** [statsd/statsd#597]
Hi all,

I just tried to "build" Statsd v0.8.0 and got the following errors from `run_test.sh`:
```
[...]
repeater_tests
��� repeater_works
Error: Expected 1 assertions, 0 ran
    at test.done (/usr/lib/node_modules/nodeunit/lib/types.js:121:25)
    at Object.test.done (/usr/lib/node_modules/nodeunit/lib/core.js:223:21)
    at Object.exports.runTest (/usr/lib/node_modules/nodeunit/lib/core.js:73:14)
    at /usr/lib/node_modules/nodeunit/lib/core.js:118:25
    at /usr/lib/node_modules/async/lib/async.js:606:13
    at iterate (/usr/lib/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/usr/lib/node_modules/async/lib/async.js:150:9)
    at _concat (/usr/lib/node_modules/async/lib/async.js:605:9)
    at Object.concatSeries (/usr/lib/node_modules/async/lib/async.js:216:23)
    at Object.exports.runSuite (/usr/lib/node_modules/nodeunit/lib/core.js:96:11)
TypeError: Cannot read property 'stop' of undefined
    at RepeaterServer.stop (/builddir/build/BUILD/statsd-0.8.0/test/repeater_tests.js:79:16)
    at stop_server (/builddir/build/BUILD/statsd-0.8.0/test/repeater_tests.js:111:23)
    at ServerSet.stop (/builddir/build/BUILD/statsd-0.8.0/test/repeater_tests.js:116:3)
    at Object.module.exports.tearDown (/builddir/build/BUILD/statsd-0.8.0/test/repeater_tests.js:131:18)
    at /usr/lib/node_modules/nodeunit/lib/core.js:260:35
    at /usr/lib/node_modules/async/lib/async.js:551:21
    at /usr/lib/node_modules/async/lib/async.js:227:13
    at iterate (/usr/lib/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/usr/lib/node_modules/async/lib/async.js:150:9)
    at _asyncMap (/usr/lib/node_modules/async/lib/async.js:226:9)
��� tcp_repeater_works
Error: Expected 1 assertions, 0 ran
    at test.done (/usr/lib/node_modules/nodeunit/lib/types.js:121:25)
    at Object.test.done (/usr/lib/node_modules/nodeunit/lib/core.js:223:21)
    at Object.exports.runTest (/usr/lib/node_modules/nodeunit/lib/core.js:73:14)
    at /usr/lib/node_modules/nodeunit/lib/core.js:118:25
    at /usr/lib/node_modules/async/lib/async.js:606:13
    at iterate (/usr/lib/node_modules/async/lib/async.js:134:13)
    at /usr/lib/node_modules/async/lib/async.js:145:25
    at /usr/lib/node_modules/async/lib/async.js:608:17
    at /usr/lib/node_modules/nodeunit/lib/types.js:146:17
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
TypeError: Cannot read property 'stop' of undefined
    at RepeaterServer.stop (/builddir/build/BUILD/statsd-0.8.0/test/repeater_tests.js:79:16)
    at stop_server (/builddir/build/BUILD/statsd-0.8.0/test/repeater_tests.js:111:23)
    at ServerSet.stop (/builddir/build/BUILD/statsd-0.8.0/test/repeater_tests.js:116:3)
    at Object.module.exports.tearDown (/builddir/build/BUILD/statsd-0.8.0/test/repeater_tests.js:131:18)
    at /usr/lib/node_modules/nodeunit/lib/core.js:260:35
    at /usr/lib/node_modules/async/lib/async.js:551:21
    at /usr/lib/node_modules/async/lib/async.js:227:13
    at iterate (/usr/lib/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/usr/lib/node_modules/async/lib/async.js:150:9)
    at _asyncMap (/usr/lib/node_modules/async/lib/async.js:226:9)
[...]
FAILURES: 4/253 assertions failed (16828ms)
```
Node Version: 5.12.0

BTW: A quid test showed the same issue appearing in `master`.

If you need any more information please let me know.

**Comment by mrtazz** [comment]
closing this since the [tests are passing on node 6, 8, 10, 11](https://travis-ci.org/statsd/statsd/builds/526030598)
